os:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017
shallow_clone: false
skip_tags: true
clone_folder: C:\SimpleElastix-source
configuration:
  - Release
platform:
  - x86
  - x64
environment:
  ITK_URL: https://github.com/InsightSoftwareConsortium/ITK
  ITK_SOURCE_DIR: C:\ITK-source
  ITK_BUILD_DIR: C:\ITK-build
  ITK_INSTALL_DIR: "C:/Program Files (x86)/ITK/lib/cmake/ITK-4.12"
  ELASTIX_URL: https://github.com/SuperElastix/elastix
  ELASTIX_SOURCE_DIR: C:\Elastix-source
  ELASTIX_BUILD_DIR: C:\Elastix-build
  SIMPLEELASTIX_SOURCE_DIR: C:\SimpleElastix-source\SuperBuild
  SIMPLEELASTIX_BUILD_DIR: C:\SimpleElastix-build
  BUILT_CACHE_STAMP: C:\BUILT_CACHE
cache:
  - '%ITK_BUILD_DIR%'
  - '%ELASTIX_BUILD_DIR%'
build_script:
  - cmd: if not exist %ITK_BUILD_DIR% git clone %ITK_URL% %ITK_SOURCE_DIR% && cd %ITK_SOURCE_DIR% && git checkout v4.12.2 && mkdir %ITK_BUILD_DIR% && cd %ITK_BUILD_DIR% && cmake -DBUILD_EXAMPLES=OFF -DBUILD_TESTING:BOOL=OFF -DCMAKE_BUILD_TYPE=Release %ITK_SOURCE_DIR% && cmake --build . --target install --config Release -- /m &&  @echo BUILT_CACHE > %BUILT_CACHE_STAMP%
  - cmd: if not exist %ELASTIX_BUILD_DIR% git clone %ELASTIX_URL% %ELASTIX_SOURCE_DIR% && cd %ELASTIX_SOURCE_DIR% && git checkout e8354222396c6bd78e9fe6d5a39e4ecac4bb0d52 && mkdir %ELASTIX_BUILD_DIR% && cd %ELASTIX_BUILD_DIR% && cmake -DITK_DIR=%ITK_BUILD_DIR% -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF %ELASTIX_SOURCE_DIR% && cmake --build . --config Release -- /m && ctest -j4 -VV -C Release && @echo BUILT_CACHE > %BUILT_CACHE_STAMP%
  - cmd: if not exist %BUILT_CACHE_STAMP% mkdir -p %SUPERELASTIX_BUILD_DIR% && cd %SUPERELASTIX_BUILD_DIR% && cmake -DUSE_SYSTEM_ITK=ON -DITK_DIR=%ITK_BUILD_DIR% -DUSE_SYSTEM_ELASTIX=ON -DElastix_DIR=%ELASTIX_BUILD_DIR% -DCMAKE_BUILD_TYPE=Release %SUPERELASTIX_SOURCE_DIR% && cmake --build . --config Release -- /m && cd SimpleElastix-build && ctest -j4 -VV -C Release 
